name: HistSys Frontend Production CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm install && HISTSYS_ENV=prod npm run-script build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm install && npm run-script build

      - name: Setup Dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
#          KEY: ${{ secrets.SSHKEY2 }}
          script: |
            mkdir -p /histsys_front/prod
            cd /histsys_front
            rm -rf ./prod
            mkdir -p ./prod
            echo "ðŸ™ŠRemove Old Source Files Success"

      - name: Copy file via scp
        uses: appleboy/scp-action@master
#        env:
##          KEY: ${{ secrets.SSHKEY2 }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: "./dist"
          target: "/histsys_front/prod/"
